kubectl delete clusterrole neuvector-binding-app 
kubectl delete clusterrole neuvector-binding-rbac 
kubectl delete clusterrolebinding neuvector-binding-app 
kubectl delete clusterrolebinding neuvector-binding-rbac 
kubectl delete clusterrole neuvector-binding-admission 
kubectl delete clusterrolebinding neuvector-binding-admission
kubectl delete clusterrole neuvector-binding-customresourcedefinition 
kubectl delete clusterrolebinding  neuvector-binding-customresourcedefinition 
kubectl delete clusterrole neuvector-binding-nvsecurityrules 
kubectl delete clusterrolebinding neuvector-binding-nvsecurityrules 
kubectl delete clusterrolebinding neuvector-binding-view 
kubectl delete rolebinding neuvector-admin